//! Parity of the `SequenceMatcher` port with CPython's difflib, against cases generated by
//! `tests/goldens/generate.py` (see `tests/goldens/README.md`).

use refactor_diff_core::{SequenceMatcher, short_hash};
use serde::Deserialize;

const GOLDENS: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../../tests/goldens");

type Op = (String, usize, usize, usize, usize);

#[derive(Deserialize)]
struct Case {
    name: String,
    junk: String,
    a: Vec<String>,
    b: Vec<String>,
    opcodes: Vec<Op>,
    matching_blocks: Vec<(usize, usize, usize)>,
    ratio: f64,
    quick_ratio: f64,
    grouped3: Vec<Vec<Op>>,
}

fn load<T: serde::de::DeserializeOwned>(name: &str) -> T {
    let text = std::fs::read_to_string(format!("{GOLDENS}/{name}")).expect("golden file");
    serde_json::from_str(&text).expect("golden json")
}

#[test]
fn seqmatch_matches_difflib() {
    let cases: Vec<Case> = load("seqmatch.json");
    assert!(cases.len() > 50);
    for case in &cases {
        let m = match case.junk.as_str() {
            "none" => SequenceMatcher::new(&case.a, &case.b),
            "blank" => SequenceMatcher::with_junk(&case.a, &case.b, |s| s.trim().is_empty()),
            other => panic!("unknown junk mode {other}"),
        };
        let blocks: Vec<(usize, usize, usize)> = m
            .matching_blocks()
            .iter()
            .map(|b| (b.a, b.b, b.size))
            .collect();
        assert_eq!(
            blocks, case.matching_blocks,
            "{}: matching_blocks",
            case.name
        );
        let ops: Vec<Op> = m
            .opcodes()
            .into_iter()
            .map(|o| (o.tag.as_str().to_string(), o.i1, o.i2, o.j1, o.j2))
            .collect();
        assert_eq!(ops, case.opcodes, "{}: opcodes", case.name);
        assert!(
            (m.ratio() - case.ratio).abs() < 1e-9,
            "{}: ratio",
            case.name
        );
        assert!(
            (m.quick_ratio() - case.quick_ratio).abs() < 1e-9,
            "{}: quick_ratio",
            case.name
        );
        let groups: Vec<Vec<Op>> = m
            .grouped_opcodes(3)
            .into_iter()
            .map(|g| {
                g.into_iter()
                    .map(|o| (o.tag.as_str().to_string(), o.i1, o.i2, o.j1, o.j2))
                    .collect()
            })
            .collect();
        assert_eq!(groups, case.grouped3, "{}: grouped_opcodes(3)", case.name);
    }
}

#[derive(Deserialize)]
struct HashCases {
    cases: Vec<HashCase>,
}

#[derive(Deserialize)]
struct HashCase {
    parts: Vec<serde_json::Value>,
    hash: String,
}

#[test]
fn short_hash_matches_python() {
    let cases: HashCases = load("short_hash.json");
    for case in cases.cases {
        let parts: Vec<String> = case
            .parts
            .iter()
            .map(|p| match p {
                serde_json::Value::String(s) => s.clone(),
                other => other.to_string(),
            })
            .collect();
        assert_eq!(short_hash(&parts), case.hash, "{:?}", case.parts);
    }
}
